/*
  Synthetic eDelphyn test database for local dashboard/chatbot testing.

  This is NOT a copy of the hospital's real eDelphyn schema (the custom
  D_DATE/D_ID/etc. types referenced throughout schema.sql are never defined
  in that file, so it can't be run as-is). Instead, this creates just the
  ~30 tables and columns that node-backend/edelphynQueries.js actually
  queries, using plain SQL Server types, and fills them with randomized
  synthetic data spanning ~14 months so every dashboard category/chart has
  something to show.

  HOW TO RUN
  1. Open this file in SSMS / Azure Data Studio, connected to the SAME
     SQL Server instance BloodBankDB already lives on (ELSAMRA-103080),
     using whatever admin login you already use there.
  2. Execute the whole script (F5). It creates a new database
     "eDelphyn_test" -- it does not touch BloodBankDB at all.
  3. Update node-backend/.env:
       EDELPHYN_DB_SERVER=ELSAMRA-103080
       EDELPHYN_DB_NAME=eDelphyn_test
       EDELPHYN_DB_USER=edelphyn_test_user
       EDELPHYN_DB_PASSWORD=EdelphynTest123!
       EDELPHYN_DB_PORT=1433
     (a scoped, read-only login is created for you at the bottom of this
     script -- same "read-only, least-privilege" pattern you'll ask the
     hospital's IT for on the real connection)
  4. Restart the Node server and open the Live Dashboard.

  Safe to re-run: drops and recreates eDelphyn_test each time.
*/

IF DB_ID('eDelphyn_test') IS NOT NULL
BEGIN
    ALTER DATABASE eDelphyn_test SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE eDelphyn_test;
END
GO

CREATE DATABASE eDelphyn_test;
GO

USE eDelphyn_test;
GO

-- ════════════════════════════════════════════════════════════════
-- LOOKUP TABLES
-- ════════════════════════════════════════════════════════════════
CREATE TABLE dbo.NATIONALITY (
    ID_NATIONALITY INT IDENTITY(1,1) PRIMARY KEY,
    DES_NATIONALITY NVARCHAR(100)
);
CREATE TABLE dbo.STATE (
    ID_STATE INT IDENTITY(1,1) PRIMARY KEY,
    DES_STATE NVARCHAR(100)
);
CREATE TABLE dbo.TOWN (
    ID_TOWN INT IDENTITY(1,1) PRIMARY KEY,
    DES_TOWN NVARCHAR(100),
    ID_STATE INT NULL REFERENCES dbo.STATE(ID_STATE)
);
CREATE TABLE dbo.CELLSEPARATOR (
    ID_CELLSEPARATOR INT IDENTITY(1,1) PRIMARY KEY,
    DES_CELLSEPARATOR NVARCHAR(100)
);
CREATE TABLE dbo.DONATIONTYPE (
    ID_DONATIONTYPE INT IDENTITY(1,1) PRIMARY KEY,
    DES_DONATIONTYPE NVARCHAR(100)
);
CREATE TABLE dbo.BAGTYPE (
    ID_BAGTYPE INT IDENTITY(1,1) PRIMARY KEY,
    COD_BAGTYPE VARCHAR(20),
    DES_BAGTYPE NVARCHAR(100)
);
CREATE TABLE dbo.DEPARTMENT (
    ID_DEPARTMENT INT IDENTITY(1,1) PRIMARY KEY,
    DES_DEPARTMENT NVARCHAR(100)
);
CREATE TABLE dbo.WARD (
    ID_WARD INT IDENTITY(1,1) PRIMARY KEY,
    DES_WARD NVARCHAR(100)
);
CREATE TABLE dbo.COMPONENTTYPE (
    ID_COMPONENTTYPE INT IDENTITY(1,1) PRIMARY KEY,
    DES_COMPONENTTYPE NVARCHAR(100)
);
CREATE TABLE dbo.COMPONENT (
    ID_COMPONENT INT IDENTITY(1,1) PRIMARY KEY,
    DES_COMPONENT NVARCHAR(100),
    ID_COMPONENTTYPE INT NULL REFERENCES dbo.COMPONENTTYPE(ID_COMPONENTTYPE)
);
CREATE TABLE dbo.ORDERTYPE (
    ID_ORDERTYPE INT IDENTITY(1,1) PRIMARY KEY,
    DES_ORDERTYPE NVARCHAR(100)
);
CREATE TABLE dbo.ORIGIN (
    ID_ORIGIN INT IDENTITY(1,1) PRIMARY KEY,
    DES_ORIGIN NVARCHAR(100)
);
CREATE TABLE dbo.DESTINATION (
    ID_DESTINATION INT IDENTITY(1,1) PRIMARY KEY,
    DES_DESTINATION NVARCHAR(100)
);
CREATE TABLE dbo.CUSTOMER (
    ID_CUSTOMER INT IDENTITY(1,1) PRIMARY KEY,
    DES_CUSTOMER NVARCHAR(100)
);
CREATE TABLE dbo.PRIORITY (
    ID_PRIORITY INT IDENTITY(1,1) PRIMARY KEY,
    DES_PRIORITY NVARCHAR(50)
);
CREATE TABLE dbo.REQUESTORIG (
    ID_REQUESTORIG INT IDENTITY(1,1) PRIMARY KEY,
    DES_REQUESTORIG NVARCHAR(100)
);
CREATE TABLE dbo.REQUESTDEST (
    ID_REQUESTDEST INT IDENTITY(1,1) PRIMARY KEY,
    DES_REQUESTDEST NVARCHAR(100)
);
GO

INSERT INTO dbo.NATIONALITY (DES_NATIONALITY) VALUES ('Lebanese'),('Syrian'),('Palestinian'),('Egyptian'),('Other');
INSERT INTO dbo.STATE (DES_STATE) VALUES ('Beirut'),('Mount Lebanon'),('North Lebanon'),('South Lebanon'),('Bekaa');
INSERT INTO dbo.TOWN (DES_TOWN, ID_STATE) VALUES
  ('Beirut', 1), ('Jounieh', 2), ('Tripoli', 3), ('Saida', 4), ('Zahle', 5), ('Baabda', 2), ('Byblos', 2);
INSERT INTO dbo.CELLSEPARATOR (DES_CELLSEPARATOR) VALUES ('Trima Accel'),('Amicus'),('Manual');
INSERT INTO dbo.DONATIONTYPE (DES_DONATIONTYPE) VALUES ('Whole Blood'),('Apheresis Platelets'),('Apheresis Plasma'),('Double Red Cells');
INSERT INTO dbo.BAGTYPE (COD_BAGTYPE, DES_BAGTYPE) VALUES ('QUAD','Quadruple Bag'),('TRIP','Triple Bag'),('DBL','Double Bag'),('SGL','Single Bag');
INSERT INTO dbo.DEPARTMENT (DES_DEPARTMENT) VALUES ('ICU'),('Emergency'),('Surgery'),('Pediatrics'),('Oncology'),('Maternity');
INSERT INTO dbo.WARD (DES_WARD) VALUES ('Ward A'),('Ward B'),('Ward C'),('ICU Ward'),('ER Ward');
INSERT INTO dbo.COMPONENTTYPE (DES_COMPONENTTYPE) VALUES ('Cellular'),('Plasma'),('Platelet');
INSERT INTO dbo.COMPONENT (DES_COMPONENT, ID_COMPONENTTYPE) VALUES
  ('Packed Red Blood Cells', 1),
  ('Fresh Frozen Plasma', 2),
  ('Platelet Concentrate', 3),
  ('Whole Blood', 1),
  ('Cryoprecipitate', 2);
INSERT INTO dbo.ORDERTYPE (DES_ORDERTYPE) VALUES ('Routine'),('Emergency'),('Cross-match');
INSERT INTO dbo.ORIGIN (DES_ORIGIN) VALUES ('Internal'),('External Referral'),('Walk-in');
INSERT INTO dbo.DESTINATION (DES_DESTINATION) VALUES ('ICU'),('Emergency'),('Surgery'),('Pediatrics'),('Oncology'),('Maternity');
INSERT INTO dbo.CUSTOMER (DES_CUSTOMER) VALUES ('Main Hospital'),('Outpatient Clinic');
INSERT INTO dbo.PRIORITY (DES_PRIORITY) VALUES ('Routine'),('Urgent'),('STAT');
INSERT INTO dbo.REQUESTORIG (DES_REQUESTORIG) VALUES ('Blood Bank'),('External Request');
INSERT INTO dbo.REQUESTDEST (DES_REQUESTDEST) VALUES
  ('St. George Hospital'),('American University Hospital'),('Rafik Hariri Hospital'),
  ('Sacre Coeur Hospital'),('Notre Dame Hospital'),('Zahra Hospital');
GO

-- ════════════════════════════════════════════════════════════════
-- CORE TABLES
-- ════════════════════════════════════════════════════════════════
CREATE TABLE dbo.PERSON (
    ID_PERSON INT IDENTITY(1,1) PRIMARY KEY,
    DES_NAME NVARCHAR(100),
    DES_MIDDLENAME NVARCHAR(100) NULL,
    DES_SURNAME NVARCHAR(100),
    ID_NATIONALITY INT NULL REFERENCES dbo.NATIONALITY(ID_NATIONALITY),
    ID_TOWN INT NULL REFERENCES dbo.TOWN(ID_TOWN),
    DES_TOWN NVARCHAR(100) NULL,
    ID_STATE INT NULL REFERENCES dbo.STATE(ID_STATE),
    COD_GROUP VARCHAR(5) NULL,
    COD_RH VARCHAR(5) NULL,
    COD_GENDER VARCHAR(1) NULL,
    DAT_BIRTH DATE NULL,
    COD_IAT VARCHAR(10) NULL
);

CREATE TABLE dbo.DONATION (
    ID_DONATION INT IDENTITY(1,1) PRIMARY KEY,
    COD_DONATION VARCHAR(30) NULL,
    DAT_DONATION DATE NULL,
    TIM_START TIME NULL,
    TIM_DONATION TIME NULL,
    ID_DONATIONTYPE INT NULL REFERENCES dbo.DONATIONTYPE(ID_DONATIONTYPE),
    ID_PERSON INT NULL REFERENCES dbo.PERSON(ID_PERSON),
    ID_BAGTYPE INT NULL REFERENCES dbo.BAGTYPE(ID_BAGTYPE),
    ID_BAGORIGIN INT NULL,
    LOG_ENTRY BIT NOT NULL DEFAULT 0,
    DAT_EXTERNALENTRY DATE NULL,
    TIM_EXTERNALENTRY TIME NULL,
    DES_BAGSERIAL VARCHAR(50) NULL,
    ID_CELLSEPARATOR INT NULL REFERENCES dbo.CELLSEPARATOR(ID_CELLSEPARATOR)
);

CREATE TABLE dbo.ORDERFORM (
    ID_ORDERFORM INT IDENTITY(1,1) PRIMARY KEY,
    DAT_ORDERFORM DATE NULL,
    TIM_ORDERFORM TIME NULL,
    COD_ORDERFORM VARCHAR(30) NULL,
    ID_PERSON INT NULL REFERENCES dbo.PERSON(ID_PERSON),
    ID_DEPARTMENT INT NULL REFERENCES dbo.DEPARTMENT(ID_DEPARTMENT),
    DES_WARD NVARCHAR(100) NULL,
    ID_WARD INT NULL REFERENCES dbo.WARD(ID_WARD),
    ID_COMPONENTTYPE INT NULL REFERENCES dbo.COMPONENTTYPE(ID_COMPONENTTYPE),
    ID_COMPONENT INT NULL REFERENCES dbo.COMPONENT(ID_COMPONENT),
    ID_ORDERTYPE INT NULL REFERENCES dbo.ORDERTYPE(ID_ORDERTYPE),
    ID_ORIGIN INT NULL REFERENCES dbo.ORIGIN(ID_ORIGIN),
    LOG_CANCELLED BIT NOT NULL DEFAULT 0,
    ID_DESTINATION INT NULL REFERENCES dbo.DESTINATION(ID_DESTINATION),
    ID_CENTRE INT NULL,
    ID_CUSTOMER INT NULL REFERENCES dbo.CUSTOMER(ID_CUSTOMER),
    ID_PRIORITY INT NULL REFERENCES dbo.PRIORITY(ID_PRIORITY)
);

CREATE TABLE dbo.SAMPLE (
    ID_SAMPLE INT IDENTITY(1,1) PRIMARY KEY,
    COD_SAMPLE VARCHAR(30) NULL,
    DAT_SAMPLE DATE NULL,
    TIM_SAMPLE TIME NULL
);
CREATE TABLE dbo.ORDERFORM_SAMPLE (
    ID_ORDERFORM INT NOT NULL REFERENCES dbo.ORDERFORM(ID_ORDERFORM),
    ID_SAMPLE INT NOT NULL REFERENCES dbo.SAMPLE(ID_SAMPLE),
    PRIMARY KEY (ID_ORDERFORM, ID_SAMPLE)
);
CREATE TABLE dbo.HOSPITALNUMBER (
    ID_PERSON INT NOT NULL REFERENCES dbo.PERSON(ID_PERSON),
    ID_CENTRE INT NULL,
    COD_HOSPITALNUMBER VARCHAR(30) NULL
);

CREATE TABLE dbo.UNIT (
    ID_UNIT INT IDENTITY(1,1) PRIMARY KEY,
    COD_UNIT VARCHAR(30) NULL,
    COD_DIVISION VARCHAR(10) NULL,
    COD_GROUP VARCHAR(5) NULL,
    COD_RH VARCHAR(5) NULL,
    ID_COMPONENT INT NULL REFERENCES dbo.COMPONENT(ID_COMPONENT),
    COD_CMV VARCHAR(10) NULL,
    COD_REJECTREASON NVARCHAR(200) NULL,
    DAT_EXPIRY DATE NULL
);

CREATE TABLE dbo.TRANSFUSION (
    ID_TRANSFUSION INT IDENTITY(1,1) PRIMARY KEY,
    DAT_TRANSFUSION DATE NULL,
    TIM_TRANSFUSION TIME NULL,
    ID_ORDERFORM INT NULL REFERENCES dbo.ORDERFORM(ID_ORDERFORM),
    ID_PERSON INT NULL REFERENCES dbo.PERSON(ID_PERSON),
    ID_UNIT INT NULL REFERENCES dbo.UNIT(ID_UNIT),
    DES_TAKENBY NVARCHAR(100) NULL,
    ID_DESTINATION INT NULL REFERENCES dbo.DESTINATION(ID_DESTINATION),
    DES_WARD NVARCHAR(100) NULL,
    ID_WARD INT NULL REFERENCES dbo.WARD(ID_WARD),
    DAT_RETURN DATE NULL,
    COD_RETURN VARCHAR(5) NOT NULL DEFAULT '0'
);

CREATE TABLE dbo.REQUEST (
    ID_REQUEST INT IDENTITY(1,1) PRIMARY KEY,
    DAT_REQUEST DATE NULL,
    TIM_REQUEST TIME NULL,
    COD_REQUEST VARCHAR(30) NULL,
    ID_REQUESTORIG INT NULL REFERENCES dbo.REQUESTORIG(ID_REQUESTORIG),
    ID_REQUESTDEST INT NULL REFERENCES dbo.REQUESTDEST(ID_REQUESTDEST),
    DAT_DELIVERY DATE NULL,
    TIM_DELIVERY TIME NULL
);
CREATE TABLE dbo.REQUESTPATIENT (
    ID_REQUEST INT PRIMARY KEY REFERENCES dbo.REQUEST(ID_REQUEST),
    DES_NAME NVARCHAR(100) NULL,
    DES_MIDDLENAME NVARCHAR(100) NULL,
    DES_SURNAME NVARCHAR(100) NULL,
    COD_BLOODTYPE VARCHAR(5) NULL,
    DES_DEPARTMENT NVARCHAR(100) NULL
);
CREATE TABLE dbo.REQUESTDETAIL (
    ID_REQUESTDETAIL INT IDENTITY(1,1) PRIMARY KEY,
    ID_REQUEST INT NOT NULL REFERENCES dbo.REQUEST(ID_REQUEST),
    ID_COMPONENTTYPE INT NULL REFERENCES dbo.COMPONENTTYPE(ID_COMPONENTTYPE),
    ID_COMPONENT INT NULL REFERENCES dbo.COMPONENT(ID_COMPONENT)
);

CREATE TABLE dbo.DELIVERYNOTE (
    ID_DELIVERYNOTE INT IDENTITY(1,1) PRIMARY KEY,
    COD_DELIVERYNOTE VARCHAR(30) NULL,
    DAT_DELIVERYNOTE DATE NULL,
    TIM_DELIVERYNOTE TIME NULL
);
CREATE TABLE dbo.DELIVERYDETAIL (
    ID_DELIVERYDETAIL INT IDENTITY(1,1) PRIMARY KEY,
    ID_REQUEST INT NOT NULL REFERENCES dbo.REQUEST(ID_REQUEST),
    ID_DELIVERYNOTE INT NULL REFERENCES dbo.DELIVERYNOTE(ID_DELIVERYNOTE),
    ID_UNIT INT NULL REFERENCES dbo.UNIT(ID_UNIT),
    ID_COMPONENT INT NULL REFERENCES dbo.COMPONENT(ID_COMPONENT),
    DAT_DELIVERYDETAIL DATE NULL,
    TIM_DELIVERYDETAIL TIME NULL,
    DAT_EXPIRY DATE NULL,
    DAT_RETURN DATE NULL,
    COD_RETURN VARCHAR(5) NOT NULL DEFAULT '0'
);

CREATE TABLE dbo.DESTROYBOX (
    ID_DESTROYBOX INT IDENTITY(1,1) PRIMARY KEY,
    COD_DESTROYBOX VARCHAR(30) NULL,
    DAT_DESTROYBOX DATE NULL,
    TIM_DESTROYBOX TIME NULL
);
CREATE TABLE dbo.DESTROYBOXUNIT (
    ID_DESTROYBOX INT NOT NULL REFERENCES dbo.DESTROYBOX(ID_DESTROYBOX),
    ID_UNIT INT NOT NULL REFERENCES dbo.UNIT(ID_UNIT),
    DAT_DESTROYBOXUNIT DATE NULL,
    TIM_DESTROYBOXUNIT TIME NULL,
    PRIMARY KEY (ID_DESTROYBOX, ID_UNIT)
);
GO

-- ════════════════════════════════════════════════════════════════
-- SYNTHETIC DATA -- randomized, spans ~14 months so month-over-month
-- charts and date filters have something to compare against.
-- ════════════════════════════════════════════════════════════════

-- 50 people, shared pool for both donors and patients
;WITH Numbers AS (
    SELECT TOP (50) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.PERSON (DES_NAME, DES_MIDDLENAME, DES_SURNAME, ID_NATIONALITY, ID_TOWN, ID_STATE, COD_GROUP, COD_RH, COD_GENDER, DAT_BIRTH, COD_IAT)
SELECT
    'Person' + CAST(n AS VARCHAR(10)),
    NULL,
    'Family' + CAST((n % 13) AS VARCHAR(10)),
    (ABS(CHECKSUM(NEWID())) % 5) + 1,
    (ABS(CHECKSUM(NEWID())) % 7) + 1,
    (ABS(CHECKSUM(NEWID())) % 5) + 1,
    CASE (ABS(CHECKSUM(NEWID())) % 4) WHEN 0 THEN 'A' WHEN 1 THEN 'B' WHEN 2 THEN 'AB' ELSE 'O' END,
    CASE (ABS(CHECKSUM(NEWID())) % 5) WHEN 0 THEN '-' ELSE '+' END,
    CASE (ABS(CHECKSUM(NEWID())) % 2) WHEN 0 THEN 'M' ELSE 'F' END,
    DATEADD(YEAR, -(18 + ABS(CHECKSUM(NEWID())) % 50), CAST(GETDATE() AS DATE)),
    CASE (ABS(CHECKSUM(NEWID())) % 20) WHEN 0 THEN 'Positive' ELSE 'Negative' END
FROM Numbers;
GO

-- 90 donations over ~14 months (~15% flagged as external entries)
;WITH Numbers AS (
    SELECT TOP (90) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.DONATION (COD_DONATION, DAT_DONATION, TIM_START, TIM_DONATION, ID_DONATIONTYPE, ID_PERSON, ID_BAGTYPE, ID_BAGORIGIN, LOG_ENTRY, DAT_EXTERNALENTRY, TIM_EXTERNALENTRY, DES_BAGSERIAL, ID_CELLSEPARATOR)
SELECT
    'DON' + RIGHT('00000' + CAST(n AS VARCHAR(10)), 5),
    d, CAST(t AS TIME), CAST(t AS TIME),
    (ABS(CHECKSUM(NEWID())) % 4) + 1,
    (ABS(CHECKSUM(NEWID())) % 50) + 1,
    (ABS(CHECKSUM(NEWID())) % 4) + 1,
    NULL,
    is_ext,
    CASE WHEN is_ext = 1 THEN d ELSE NULL END,
    CASE WHEN is_ext = 1 THEN CAST(t AS TIME) ELSE NULL END,
    'BAG' + CAST(100000 + n AS VARCHAR(10)),
    (ABS(CHECKSUM(NEWID())) % 3) + 1
FROM (
    SELECT n,
        DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)) AS d,
        DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00') AS t,
        CASE WHEN ABS(CHECKSUM(NEWID())) % 100 < 15 THEN 1 ELSE 0 END AS is_ext
    FROM Numbers
) x;
GO

-- 90 order forms over ~14 months (~8% cancelled -- should be excluded by the query)
;WITH Numbers AS (
    SELECT TOP (90) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.ORDERFORM (DAT_ORDERFORM, TIM_ORDERFORM, COD_ORDERFORM, ID_PERSON, ID_DEPARTMENT, DES_WARD, ID_WARD, ID_COMPONENTTYPE, ID_COMPONENT, ID_ORDERTYPE, ID_ORIGIN, LOG_CANCELLED, ID_DESTINATION, ID_CENTRE, ID_CUSTOMER, ID_PRIORITY)
SELECT
    d, CAST(t AS TIME),
    'OF' + RIGHT('00000' + CAST(n AS VARCHAR(10)), 5),
    (ABS(CHECKSUM(NEWID())) % 50) + 1,
    (ABS(CHECKSUM(NEWID())) % 6) + 1,
    NULL,
    (ABS(CHECKSUM(NEWID())) % 5) + 1,
    (ABS(CHECKSUM(NEWID())) % 3) + 1,
    (ABS(CHECKSUM(NEWID())) % 5) + 1,
    (ABS(CHECKSUM(NEWID())) % 3) + 1,
    (ABS(CHECKSUM(NEWID())) % 3) + 1,
    cancelled,
    (ABS(CHECKSUM(NEWID())) % 6) + 1,
    1,
    (ABS(CHECKSUM(NEWID())) % 2) + 1,
    (ABS(CHECKSUM(NEWID())) % 3) + 1
FROM (
    SELECT n,
        DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)) AS d,
        DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00') AS t,
        CASE WHEN ABS(CHECKSUM(NEWID())) % 100 < 8 THEN 1 ELSE 0 END AS cancelled
    FROM Numbers
) x;
GO

-- Samples + link to ~50 order forms
;WITH Numbers AS (
    SELECT TOP (50) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.SAMPLE (COD_SAMPLE, DAT_SAMPLE, TIM_SAMPLE)
SELECT 'SMP' + RIGHT('00000' + CAST(n AS VARCHAR(10)), 5),
    DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)),
    DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00')
FROM Numbers;
GO
INSERT INTO dbo.ORDERFORM_SAMPLE (ID_ORDERFORM, ID_SAMPLE)
SELECT TOP (50) ID_ORDERFORM, ID_SAMPLE
FROM dbo.ORDERFORM CROSS JOIN dbo.SAMPLE
GROUP BY ID_ORDERFORM, ID_SAMPLE
ORDER BY NEWID();
GO

-- Hospital numbers for ~30 people
INSERT INTO dbo.HOSPITALNUMBER (ID_PERSON, ID_CENTRE, COD_HOSPITALNUMBER)
SELECT TOP (30) ID_PERSON, 1, 'HN' + RIGHT('00000' + CAST(ID_PERSON AS VARCHAR(10)), 5)
FROM dbo.PERSON ORDER BY NEWID();
GO

-- 150 units: 1-60 for transfusions, 61-100 for deliveries, 101-150 for destroyed
;WITH Numbers AS (
    SELECT TOP (150) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.UNIT (COD_UNIT, COD_DIVISION, COD_GROUP, COD_RH, ID_COMPONENT, COD_CMV, COD_REJECTREASON, DAT_EXPIRY)
SELECT
    'U' + RIGHT('000000' + CAST(n AS VARCHAR(10)), 6),
    CASE WHEN n % 4 = 0 THEN 'A' ELSE '' END,
    CASE (ABS(CHECKSUM(NEWID())) % 4) WHEN 0 THEN 'A' WHEN 1 THEN 'B' WHEN 2 THEN 'AB' ELSE 'O' END,
    CASE (ABS(CHECKSUM(NEWID())) % 5) WHEN 0 THEN '-' ELSE '+' END,
    (ABS(CHECKSUM(NEWID())) % 5) + 1,
    CASE (ABS(CHECKSUM(NEWID())) % 4) WHEN 0 THEN 'Negative' ELSE 'Positive' END,
    CASE WHEN n > 100 THEN
        CASE (ABS(CHECKSUM(NEWID())) % 5)
            WHEN 0 THEN 'Expired'
            WHEN 1 THEN 'Hemolysis'
            WHEN 2 THEN 'Broken Bag'
            WHEN 3 THEN 'Positive Serology'
            ELSE 'Clotted'
        END
    ELSE NULL END,
    DATEADD(DAY, (ABS(CHECKSUM(NEWID())) % 60) - 30, CAST(GETDATE() AS DATE))
FROM Numbers;
GO

-- 90 transfusions over ~14 months using units 1-60 (~15% returned)
;WITH Numbers AS (
    SELECT TOP (90) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.TRANSFUSION (DAT_TRANSFUSION, TIM_TRANSFUSION, ID_ORDERFORM, ID_PERSON, ID_UNIT, DES_TAKENBY, ID_DESTINATION, DES_WARD, ID_WARD, DAT_RETURN, COD_RETURN)
SELECT
    d, CAST(t AS TIME),
    (ABS(CHECKSUM(NEWID())) % 90) + 1,
    (ABS(CHECKSUM(NEWID())) % 50) + 1,
    (ABS(CHECKSUM(NEWID())) % 60) + 1,
    'Nurse ' + CAST((ABS(CHECKSUM(NEWID())) % 12) + 1 AS VARCHAR(10)),
    (ABS(CHECKSUM(NEWID())) % 6) + 1,
    NULL,
    (ABS(CHECKSUM(NEWID())) % 5) + 1,
    CASE WHEN returned = 1 THEN DATEADD(DAY, 1, d) ELSE NULL END,
    CASE WHEN returned = 1 THEN '1' ELSE '0' END
FROM (
    SELECT n,
        DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)) AS d,
        DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00') AS t,
        CASE WHEN ABS(CHECKSUM(NEWID())) % 100 < 15 THEN 1 ELSE 0 END AS returned
    FROM Numbers
) x;
GO

-- 60 requests (external-delivery workflow) + delivery notes/details using units 61-100
;WITH Numbers AS (
    SELECT TOP (60) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.REQUEST (DAT_REQUEST, TIM_REQUEST, COD_REQUEST, ID_REQUESTORIG, ID_REQUESTDEST, DAT_DELIVERY, TIM_DELIVERY)
SELECT
    d, CAST(t AS TIME),
    'REQ' + RIGHT('00000' + CAST(n AS VARCHAR(10)), 5),
    (ABS(CHECKSUM(NEWID())) % 2) + 1,
    (ABS(CHECKSUM(NEWID())) % 6) + 1,
    d, CAST(t AS TIME)
FROM (
    SELECT n,
        DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)) AS d,
        DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00') AS t
    FROM Numbers
) x;
GO

;WITH Numbers AS (
    SELECT TOP (60) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.DELIVERYNOTE (COD_DELIVERYNOTE, DAT_DELIVERYNOTE, TIM_DELIVERYNOTE)
SELECT 'DN' + RIGHT('00000' + CAST(n AS VARCHAR(10)), 5),
    DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)),
    DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00')
FROM Numbers;
GO

INSERT INTO dbo.DELIVERYDETAIL (ID_REQUEST, ID_DELIVERYNOTE, ID_UNIT, ID_COMPONENT, DAT_DELIVERYDETAIL, TIM_DELIVERYDETAIL, DAT_EXPIRY, DAT_RETURN, COD_RETURN)
SELECT
    (ABS(CHECKSUM(NEWID())) % 60) + 1,
    (ABS(CHECKSUM(NEWID())) % 60) + 1,
    (ABS(CHECKSUM(NEWID())) % 40) + 61,   -- units 61-100
    (ABS(CHECKSUM(NEWID())) % 5) + 1,
    d, CAST(t AS TIME),
    -- ~20% expiring within 2 weeks of delivery, to exercise the near-expiry alert
    CASE WHEN near_exp = 1 THEN DATEADD(DAY, (ABS(CHECKSUM(NEWID())) % 10) + 1, d) ELSE DATEADD(DAY, 30, d) END,
    CASE WHEN returned = 1 THEN DATEADD(DAY, 1, d) ELSE NULL END,
    CASE WHEN returned = 1 THEN '1' ELSE '0' END
FROM (
    SELECT
        DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)) AS d,
        DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00') AS t,
        CASE WHEN ABS(CHECKSUM(NEWID())) % 100 < 20 THEN 1 ELSE 0 END AS near_exp,
        CASE WHEN ABS(CHECKSUM(NEWID())) % 100 < 10 THEN 1 ELSE 0 END AS returned
    FROM (SELECT TOP (70) n FROM (SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n FROM sys.all_objects) z) Numbers
) x;
GO

-- 50 destroy boxes + destroyed units using units 101-150
;WITH Numbers AS (
    SELECT TOP (50) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_objects
)
INSERT INTO dbo.DESTROYBOX (COD_DESTROYBOX, DAT_DESTROYBOX, TIM_DESTROYBOX)
SELECT 'DB' + RIGHT('00000' + CAST(n AS VARCHAR(10)), 5),
    DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 420, CAST(GETDATE() AS DATE)),
    DATEADD(MINUTE, ABS(CHECKSUM(NEWID())) % 1440, '00:00')
FROM Numbers;
GO

INSERT INTO dbo.DESTROYBOXUNIT (ID_DESTROYBOX, ID_UNIT, DAT_DESTROYBOXUNIT, TIM_DESTROYBOXUNIT)
SELECT db.ID_DESTROYBOX, u.ID_UNIT, db.DAT_DESTROYBOX, db.TIM_DESTROYBOX
FROM dbo.DESTROYBOX db
INNER JOIN dbo.UNIT u ON u.ID_UNIT = 100 + db.ID_DESTROYBOX;  -- units 101-150, one per box
GO

PRINT 'eDelphyn_test created and seeded.';
GO

-- ════════════════════════════════════════════════════════════════
-- Optional: scoped, read-only login for the app to use instead of
-- your admin account -- same least-privilege pattern to ask the
-- hospital's IT for on the real connection.
-- ════════════════════════════════════════════════════════════════
USE master;
GO
IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = 'edelphyn_test_user')
    CREATE LOGIN edelphyn_test_user WITH PASSWORD = 'EdelphynTest123!', CHECK_POLICY = OFF;
GO
USE eDelphyn_test;
GO
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'edelphyn_test_user')
    CREATE USER edelphyn_test_user FOR LOGIN edelphyn_test_user;
GO
ALTER ROLE db_datareader ADD MEMBER edelphyn_test_user;
GO

PRINT 'Read-only login edelphyn_test_user created on eDelphyn_test.';
GO
